name: tubeProAid
channels:
  - conda-forge
  - defaults
dependencies:
  - beaupy=3.10.0=pyhd8ed1ab_0
  - chardet=5.2.0=py311h1ea47a8_2
  - easyocr=1.7.0=py311h214f63a_0
  - emoji=2.10.1=pyhd8ed1ab_0
  - ninja=1.12.1=hc790b64_0
  - numpy=1.26.4=py311h0b4df5a_0
  - pillow=11.1.0=py311h43e43bb_0
  - psutil=6.1.1=py311he736701_0
  - pyinstaller=6.11.1=py311ha408274_0
  - pynput=1.7.7=py311h1ea47a8_1
  - python=3.11.11=h3f84c4b_1_cpython
  - striprtf=0.0.28=pyhd8ed1ab_1
  - pip:
      - dearpygui==2.0.0
